### PR TITLE
EVG-14007 log user of request

### PR DESCRIPTION
**Pull request by ablack12**
If there's already a way to see this I can close out.

### CODE REVIEW

**Comment by john-m-liu** [comment]
This should already be logged in https://github.com/evergreen-ci/gimlet/blob/5a704471d124e95f37fea15e98736bf84c87d4f8/middleware_auth.go#L184. Does this cover cases that one doesn't?

**Comment by ablack12** [comment]
Hmm if I look at something logged [here](https://mongodb.splunkcloud.com/en-US/app/search/search?q=search%20index%3Devergreen%20task_history%20test_names&display.page.search.mode=verbose&dispatch.sample_ratio=1&earliest=-30m%40m&latest=now&workload_pool=standard_perf&sid=1614099563.1276233) and I search the "remote" value, I don't see anything in that form you shared.  I think this is because for the UI we use a [different middleware](https://github.com/evergreen-ci/evergreen/blob/83ce966917b03eae96b566ba54c29c3882789be5/service/ui.go#L244).

**Comment by ablack12** [comment]
I could add this to that ServeHTTP instead if that seems more consistent.

**Comment by john-m-liu** [comment]
I think that'd be better, because I think this one will get the user twice for non-UI routes. It is more work though since you'll have to take out the middleware wrapper, but hopefully it's not much more

**Comment by john-m-liu** [comment]
oh wait but doing that requires logging twice which is worse

**Review by john-m-liu — APPROVED** [review]

**Pull request merged**
